apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  namespace: default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 5
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: charlesjatto/java-web-app:1
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: default
spec:
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  type: NodePort
