apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-myapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: charlesjatto/java-web-app:1
          ports:
            - name: http
              containerPort: 8080
